import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { promoteFinalGateEvidence } from "../scripts/production/final-gate-evidence-promote.mjs";

const sha = (bytes) => createHash("sha256").update(bytes).digest("hex");
const base = (repository, check) => ({ schemaVersion:1, check, repository, commit:"a".repeat(40), runId:"123456", runAttempt:"1", recordedAt:"2026-10-06T20:15:00Z" });
const atlas = () => ({ ...base("Emmakex/puente-deca","deca-atlas-core-acceptance"), scope:"deca-only", result:{ status:"ok", check:"deca-atlas-core-acceptance", scope:"deca-only", database:"kairoseth", artifactBucket:"deca_pdf", steps:{preflight:true,atlasGridFs:true,atlasConcurrency:true,artifactReconciliation:true}, evidence:{metadataPing:true,artifactPing:true,indexContract:true,transactionRollback:true,gridfsRoundTrip:true,gridfsCleanup:true,idempotencyConcurrency:true,idempotencyConverged:true,documentVersionConcurrency:true,documentLineageConsistent:true,cleanupVerified:true}, reconciliation:{references:1,storedArtifacts:1,purgeRecords:0,missingBeforeRetention:0,missingAfterRetention:0,orphanedArtifacts:0,purgedArtifactsStillPresent:0} } });
const dr = () => ({ ...base("Emmakex/puente-deca","puente-deca-backup-restore-production-acceptance"), result:{ status:"ok", check:"puente-deca-backup-restore-acceptance", backup:{bytes:100,sha256:`sha256:${"b".repeat(64)}`,namespaces:["kairoseth.shipments"],sourceCollectionSetSha256:`sha256:${"c".repeat(64)}`}, restore:{database:"kairoseth_deca_dr_test",allArtifactsVerified:true,artifactsVerified:1,artifactBytesVerified:100,metadataArtifactLinksVerified:1,reconciliation:{missingBeforeRetention:0,missingAfterRetention:0,orphanedArtifacts:0,purgedArtifactsStillPresent:0},cleanedUp:true,preserved:false} } });
const engine = () => ({ ...base("Emmakex/kairoseth-platform","kairoseth-cargo-engine-production-acceptance"), readOnly:true,productionMutations:false,shipmentIdSha256:`sha256:${"d".repeat(64)}`,publicPdfUrlSha256:`sha256:${"e".repeat(64)}`,pdfSha256:`sha256:${"f".repeat(64)}`,publicHeaderPrivacy:"passed",engineBridge:"passed" });
const edge = () => ({ ...base("Emmakex/kairoseth-platform","kairoseth-cargo-hostinger-edge-acceptance"), publicPdfUrlSha256:`sha256:${"1".repeat(64)}`,pdfSha256:`sha256:${"2".repeat(64)}`,httpStatus:200,tlsVerified:true,hostingerCdnObserved:true,contentSecurityPolicyFailClosed:true,remoteIp:"203.0.113.1",safeReplayRequests:8,tamperedTokenStatus:404,pathTraversalStatus:404,forbiddenHeaderLeak:false,volumetricLoadTestPerformed:false });

async function fixture(value){const dir=await mkdtemp(path.join(os.tmpdir(),"deca-final-gate-"));const evidencePath=path.join(dir,"acceptance-evidence.json");const checksumPath=`${evidencePath}.sha256`;const bytes=Buffer.from(`${JSON.stringify(value,null,2)}\n`);await writeFile(evidencePath,bytes);await writeFile(checksumPath,`${sha(bytes)}  acceptance-evidence.json\n`);return{dir,evidencePath,checksumPath};}
async function positive(gateName,factory){const f=await fixture(factory());try{const out=await promoteFinalGateEvidence({gateName,evidencePath:f.evidencePath,checksumPath:f.checksumPath});assert.equal(out.status,"ok");assert.equal(out.gateName,gateName);assert.deepEqual(Object.keys(out.gate).sort(),["commit","evidenceSha256","recordedAt","repository","runId","status"]);assert.equal(out.gate.status,"pass");}finally{await rm(f.dir,{recursive:true,force:true});}}

test("promotes Atlas core evidence",()=>positive("atlasCore",atlas));
test("promotes DR restore evidence",()=>positive("drRestore",dr));
test("promotes Kairoseth engine evidence",()=>positive("kairosethEngine",engine));
test("promotes Hostinger edge evidence",()=>positive("hostingerEdge",edge));

test("rejects checksum tampering",async()=>{const f=await fixture(atlas());try{await writeFile(f.evidencePath,"{}\n");await assert.rejects(promoteFinalGateEvidence({gateName:"atlasCore",evidencePath:f.evidencePath,checksumPath:f.checksumPath}),(e)=>e?.code==="FINAL_GATE_CHECKSUM_MISMATCH");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("rejects Atlas anomalies",async()=>{const v=atlas();v.result.reconciliation.orphanedArtifacts=1;const f=await fixture(v);try{await assert.rejects(promoteFinalGateEvidence({gateName:"atlasCore",evidencePath:f.evidencePath,checksumPath:f.checksumPath}),(e)=>e?.code==="FINAL_GATE_RESULT_INVALID");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("rejects preserved DR database",async()=>{const v=dr();v.result.restore.preserved=true;const f=await fixture(v);try{await assert.rejects(promoteFinalGateEvidence({gateName:"drRestore",evidencePath:f.evidencePath,checksumPath:f.checksumPath}),(e)=>e?.code==="FINAL_GATE_RESULT_INVALID");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("rejects mutating engine evidence",async()=>{const v=engine();v.productionMutations=true;const f=await fixture(v);try{await assert.rejects(promoteFinalGateEvidence({gateName:"kairosethEngine",evidencePath:f.evidencePath,checksumPath:f.checksumPath}),(e)=>e?.code==="FINAL_GATE_RESULT_INVALID");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("rejects volumetric edge evidence",async()=>{const v=edge();v.volumetricLoadTestPerformed=true;const f=await fixture(v);try{await assert.rejects(promoteFinalGateEvidence({gateName:"hostingerEdge",evidencePath:f.evidencePath,checksumPath:f.checksumPath}),(e)=>e?.code==="FINAL_GATE_RESULT_INVALID");}finally{await rm(f.dir,{recursive:true,force:true});}});
test("rejects secret-bearing evidence",async()=>{const v=engine();v.secret="should-not-exist";const f=await fixture(v);try{await assert.rejects(promoteFinalGateEvidence({gateName:"kairosethEngine",evidencePath:f.evidencePath,checksumPath:f.checksumPath}),(e)=>e?.code==="FINAL_GATE_EVIDENCE_SECRET_MATERIAL");}finally{await rm(f.dir,{recursive:true,force:true});}});
